theme: jekyll-theme-slate
title: Sartell Coder Dojo
url: https://sartellcoderdojo.org
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/sartell-coder-dojo/sartell-coder-dojo.github.io
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
