theme: jekyll-theme-slate
title: Sartell Coder Dojo
url: https://sartellcoderdojo.org
show_downloads: true
github:
  is_project_page: true
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
